server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/UserService
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
  application:
    name: UserService

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka