spring:
  datasource:
    url: jdbc:mysql://localhost:3306/RatingService
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  application:
    name: RatingService

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8000/eureka

server:
  port: 8082